```{r}
set.seed(9432142)

simulate = function(
  n_cosines, n_outputs, turnover, eta, pretraining=T, post_training=T, homeostasis=T) {
  
  threshold_function = function(x) {x[x - quantile(x, .9) < 0]=0;x}
  
  # Initialize inputs and synaptic weights
  orginal_input_idx = sample(1:10000, n_cosines)
  new_input_idx = sample(which(!(1:10000) %in% orginal_input_idx), turnover)
  input = all_grid_cells[,orginal_input_idx]
  weights = replicate(n_outputs, sample(synaptic_strength_pool, size=n_cosines, replace=T))
  #weights %<>% apply(2, function(x) 148.7*x/sum(x))
  replacement_input = all_grid_cells[,new_input_idx]
  
  # save original weights
  df_weights = data.frame(original_weights = c(weights))
  
  # Activate the output units pre-turnover
  response = input %*% weights
  response %<>% apply(2, threshold_function)
  
  # Pre-training
  if (pretraining) {
    dw = np$dot(t(input), response)
    weights = weights + eta*dw
    if (homeostasis) weights %<>% apply(2, function(x) 148.7*x/sum(x))
  }
  
  # Save trained weights
  df_weights$trained_weights = c(weights)
  
  # Save weights and inputs
  inputs_pre_turnover = input
  weights_pre_turnover = weights
  
  # Synpase turnover
  input[,1:turnover] = replacement_input
  weights[1:turnover,] = sample(synaptic_strength_pool, size=turnover*n_outputs, replace=T)

  # Activate the output units post-turnover
  response = input %*% weights
  response %<>% apply(2, threshold_function)
  
  # Post-training
  if (post_training) {
    dw = np$dot(t(input), response)
    weights = weights + eta*dw
    if (homeostasis) weights %<>% apply(2, function(x) 148.7*x/sum(x))
  }
  
  # Save trained/post-turnover weights
  df_weights$post_turnover_weights = c(weights)
  
  # Sum synaptic potentials across replaced inputs
  PSP_pre_turnover = inputs_pre_turnover[,1:turnover] %*% weights_pre_turnover[1:turnover,]
  PSP_post_turnover = input[,1:turnover] %*% weights[1:turnover,]
  
  # Get correlation between PSPs pre and post-turnover
  correlation = cor(c(PSP_pre_turnover), c(PSP_post_turnover))

  return(list(w=df_weights, c=correlation))
}

result = 
  sapply(1:10, function(replicate_number) {
    eta = c(1, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7)
    sapply(eta, function(eta) {
      bind_rows(
        simulate(
          n_cosines=1200, n_outputs=1, turnover=120, 
          eta=eta, pretraining=T, post_training=T,
          homeostasis=T
          )$w %>%
          mutate(Eta = eta, Scaling=T),
        simulate(
          n_cosines=1200, n_outputs=1, turnover=120, 
          eta=eta, pretraining=T, post_training=T,
          homeostasis=F
          )$w %>%
          mutate(Eta = eta, Scaling=F)
        )
    }, simplify=F) %>%
    bind_rows() %>%
      mutate(replicate_number=replicate_number)
  }, simplify=F) %>%
  bind_rows()
```

```{r, fig.height=2, fig.width=2.5}
eta = c(1, 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7)

g_delta_vs_original_strength =
  result %>%
  mutate(Scaling = ifelse(Scaling, "Scaling", "No scaling")) %>%
  mutate(delta = abs(trained_weights - original_weights)) %>%
  group_by(Scaling, Eta) %>%
  summarise(SE=sd(delta)/sqrt(length(delta)), delta=mean(delta)) %>%
  mutate(Eta=as.numeric(factor(Eta))) %>%
  ggplot(aes(Eta, delta, color=Scaling, group=Scaling)) +
  geom_hline(yintercept=mean(result$original_weights), lty=2) +
  geom_line() +
  geom_segment(aes(x=Eta-.4, xend=Eta+.4, y=delta, yend=delta+SE)) +
  geom_segment(aes(x=Eta-.4, xend=Eta+.4, y=delta, yend=delta-SE)) +
  geom_point(stat="summary", fun.data="mean_se", shape=21, fill="white") +
  scale_y_log10(breaks=c(1e-4, 1e-3, 1e-2, 1e-1, 1, 1e1, 1e2, 1e3, 1e4, 1e5)) +
  scale_x_continuous(breaks=1:8, labels=rev(as.character(eta))) +
  labs(x="Learning rate", y=TeX("$\\Delta$ Synaptic strength")) +
  scale_color_manual(values=c("cornflowerblue", "seagreen2")) +
  theme(
    axis.text.x = element_text(angle=45, hjust=1),
    legend.position=c(.3, .9),
    legend.title = element_blank()
    ) +
  guides(color=guide_legend(keywidth = .5, keyheight = .5)) +
  annotate("text", x=2.2, y=.25, label="Mean strength", size=2)

g_delta_vs_original_strength
```


