```{r}
set.seed(1234)

# values to save
place_cells_day_30_untrained = NULL
place_cells_day_29 = NULL

# parameters
X = load_input() # grid cell firing rates
n_units = 2000 # number of place cells
n_inputs = 10000 # number of grid cells
initial_weight_value = 1/1200
turnover_fraction = 114/1200

# day zero
place_cells = initialize_place_cells(n_units, n_inputs, initial_weight_value)
place_cells = calculate_firing_rates(place_cells, X)
place_cells = update_place_cell_weights(place_cells, X, learning_rule="LTP and LTD")

# reactivations
for (day in 1:30) {
  place_cells = turnover(place_cells)
  if (day == 30) place_cells_day_30_untrained = place_cells # save value
  place_cells = calculate_firing_rates(place_cells, X)
  place_cells = update_place_cell_weights(place_cells, X, learning_rule="LTP and LTD")
  if (day == 29) place_cells_day_29 = place_cells # save value
}

lost_synapses = place_cells$synapses == 0 & place_cells_day_29$synapses == 1
new_synapses = place_cells$synapses == 1 & place_cells_day_29$synapses == 0

y_day_29 = np$dot(X, place_cells_day_29$weights*lost_synapses)
y_day_30_untrained = np$dot(X, place_cells_day_30_untrained$weights*new_synapses)
y_day_30_trained = np$dot(X, place_cells$weights*new_synapses)

correlations_untrained = cor(t(y_day_29), t(y_day_30_untrained)) %>% diag()
correlations_trained = cor(t(y_day_29), t(y_day_30_trained)) %>% diag()
df = data.frame(
    Untrained=correlations_untrained, 
    Trained=correlations_trained
  ) %>%
  gather(Condition, Correlation) %>%
  mutate(Condition=factor(Condition, levels=c("Untrained", "Trained")))
g_correlations = ggplot(df, aes(Correlation, color=Condition)) +
  geom_step(stat="ecdf") +
  geom_vline(xintercept=0, linetype=2) +
  geom_hline(yintercept=.5, linetype=2) +
  xlab(TeX("$r(PSPs_{new}, PSPs_{lost})$")) +
  ylab("Cum. dens.") +
  scale_x_continuous(breaks=c(0, .1, .2)) +
  scale_color_manual(values=c("black", "red3")) +
  theme(
    legend.title = element_blank(),
    legend.position = c(.5, .75),
    legend.background = element_rect(fill=NA, color=NA)
  ) +
  guides(color=guide_legend(keywidth = .5, keyheight = .5))
g_correlations
```

```{r}
df %>%
  mutate(Positive_cor = Correlation > 0) %>%
  group_by(Condition) %>%
  summarise(sum(Positive_cor))
```

