```{r}
library(plyr); library(dplyr); library(reshape2); 
library(scales); library(ggplot2); library(cowplot)

set.seed(1234)
```

```{r}
make_cosines = function(n_cosines) {
  x = seq(0, 2*pi, length=100)
  
  period = runif(n_cosines, min=pi/4, max=2*pi)
  phase = runif(n_cosines, min=0, max=2*pi)
  
  B = 2*pi / period
  C = phase * -B
  
  cosines = mapply(function(B, C) sin(B*x+C), B=period, C=phase)
  return(cosines)
}
```


```{r}
n_cosines = 15

cosines = make_cosines(n_cosines=n_cosines) %>% 
  scales::rescale(to=c(0,1), from=c(-1, 1))
weights = rnorm(n_cosines)
PSP_sum = (cosines %*% weights) %>% scale(center=T, scale=F)

to_replace = c(3, 5, 9, 10, 14)

df_cosines = melt(cosines) %>%
  ddply(c("Var2"), function(df) mutate(df, value=value+Var2*2)) %>%
  mutate(replace=Var2 %in% to_replace)

replacement_cosines = make_cosines(n_cosines=5) %>% 
  scales::rescale(to=c(0,1), from=c(-1, 1))
replacement = cosines
replacement[,to_replace] = replacement_cosines
df_replacement = melt(replacement) %>%
  ddply(c("Var2"), function(df) mutate(df, value=value+Var2*2)) %>%
  mutate(replace=Var2 %in% to_replace)

g_top = ggplot(df_cosines, aes(Var1, value, group=Var2, color=replace)) +
  theme_void() +
  geom_line() + 
  xlim(-160, 250) +
  annotate("line", x=c(-150, -50), y=c(12.5, 19.5)) +
  annotate("line", x=151:250, y=PSP_sum+16) +
  annotate("segment", x=-40, y=seq(12, 20, length=15), xend=-10, yend=seq(2.5, 30.5, length=15)) +
  annotate("segment", x=110, y=seq(2.5, 30.5, length=15), xend=140, yend=seq(12, 20, length=15)) +
  annotate("point", x=140, y=seq(12, 20, length=15), size=0.5) +
  annotate("point", x=-10, y=seq(2.5, 30.5, length=15), size=0.5) +
  annotate("text", x=c(-100, 50, 200), y=c(22, 33, 22), label=c("Sensory afferent", "Layer 1", "Layer 2")) +
  scale_color_manual(values=c("black", "red")) +
  theme(legend.position = "none")

g_bottom = ggplot(df_replacement, aes(Var1, value, group=Var2, color=replace)) +
  theme_void() +
  geom_line() + 
  xlim(-160, 250) +
  annotate("line", x=c(-150, -50), y=c(12.5, 19.5)) +
  annotate("line", x=151:250, y=PSP_sum+16) +
  annotate("segment", x=-40, y=seq(12, 20, length=15), xend=-10, yend=seq(2.5, 30.5, length=15)) +
  annotate("segment", x=110, y=seq(2.5, 30.5, length=15), xend=140, yend=seq(12, 20, length=15)) +
  annotate("point", x=140, y=seq(12, 20, length=15), size=0.5) +
  annotate("point", x=-10, y=seq(2.5, 30.5, length=15), size=0.5) +
  annotate("path", x=c(-155, -155, -143), y=c(14, 11, 11)) +
  annotate("text", x=c(-149, -158), y=c(10, 12.5), label=c("t", "r"), size=3) +
  scale_color_manual(values=c("black", "blue")) +
  theme(legend.position = "none")

figure = ggdraw() +
  draw_plot(g_top, x = 0, y = .5, width = 1, height = .5) +
  draw_plot(g_bottom, x = 0, y = 0, width = 1, height = .5) +
  draw_plot_label(label = c("A", "B"), size = 10, x = c(0, 0), y = c(1, .5))

figure # Make plot
```

```{r}
tiff("FIGURE1.tiff", width = 6.18, height = 4, units = 'in', res = 300, compression = 'none')
figure # Make plot
dev.off()
```
